seed: 1107
device: cuda:0
num_steps_per_env: 24
max_iterations: 60
empirical_normalization: {}
obs_groups: {}
clip_actions: null
check_for_nan: true
save_interval: 1
experiment_name: drobot_pure_stairs_first_step_landing_hip_180x250_direct
run_name: landing-from-deterministic-lift-seed1107
logger: tensorboard
neptune_project: isaaclab
wandb_project: isaaclab
resume: true
load_run: bootstrap-from-lift-consolidate-model418
load_checkpoint: model_418.pt
class_name: OnPolicyRunner
actor:
  class_name: MLPModel
  hidden_dims:
  - 256
  - 256
  activation: elu
  obs_normalization: true
  distribution_cfg:
    class_name: GaussianDistribution
    init_std: 0.6
    std_type: scalar
critic:
  class_name: MLPModel
  hidden_dims:
  - 256
  - 256
  activation: elu
  obs_normalization: true
  distribution_cfg: null
algorithm:
  class_name: PPO
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.0001
  schedule: adaptive
  gamma: 0.995
  lam: 0.95
  entropy_coef: 0.002
  desired_kl: 0.01
  max_grad_norm: 1.0
  optimizer: adam
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  normalize_advantage_per_mini_batch: false
  share_cnn_encoders: false
  rnd_cfg: null
  symmetry_cfg: null
policy: {}
