"""Printable quadruped body tub with hip reinforcement and internal bays.

Coordinate convention:
    - origin: center of the body footprint at the bottom surface
    - +X: robot front
    - +Y: robot left
    - +Z: up

The structural tub is deliberately one printable solid.  A separate removable
lid and electronics tray are generated by their own thin wrapper modules.
"""

from __future__ import annotations

from pathlib import Path

from build123d import Align, Axis, Box, Cylinder, Location, Shape, fillet

PROJECT_ROOT = Path(__file__).resolve().parents[2]

# X2D-safe exterior.  With a 5 mm brim, the 230 x 180 mm print footprint fits
# inside the 235.5 x 256 mm shared dual-nozzle region.
BODY_LENGTH_X_MM = 220.0
BODY_WIDTH_Y_MM = 170.0
BODY_TOTAL_HEIGHT_Z_MM = 100.0
BODY_BASE_HEIGHT_Z_MM = 96.0
BODY_LID_THICKNESS_Z_MM = BODY_TOTAL_HEIGHT_Z_MM - BODY_BASE_HEIGHT_Z_MM
BODY_CORNER_RADIUS_MM = 12.0
BODY_WALL_MM = 3.2
BODY_FLOOR_MM = 4.0
BOOLEAN_OVERTRAVEL_MM = 1.0
FUSION_OVERLAP_MM = 0.5

# Existing 76 x 76 mm hip plates sit on the two long side walls.
HIP_MOUNT_CENTER_X_MM = 60.0
HIP_MOUNT_CENTER_Z_MM = 50.0
HIP_MOUNT_PATTERN_X_MM = 60.0
HIP_MOUNT_PATTERN_Z_MM = 60.0
HIP_BODY_CLEARANCE_DIAMETER_MM = 4.8
HIP_MOUNT_CENTERS_X_MM = (-HIP_MOUNT_CENTER_X_MM, HIP_MOUNT_CENTER_X_MM)
HIP_MOUNT_HOLE_X_MM = (-90.0, -30.0, 30.0, 90.0)
HIP_MOUNT_HOLE_Z_MM = (20.0, 80.0)

# Oversized inside pads increase the local wall from 3.2 mm to 6.0 mm and tie
# each plate field into the floor and top rim.
HIP_BACKING_PAD_LENGTH_X_MM = 84.0
HIP_BACKING_PAD_HEIGHT_Z_MM = 92.5
HIP_BACKING_TOTAL_THICKNESS_Y_MM = 6.0

# Provisional battery envelope.  Exact hardware is intentionally not frozen.
BATTERY_CLEAR_LENGTH_X_MM = 168.0
BATTERY_CLEAR_WIDTH_Y_MM = 68.0
BATTERY_CLEAR_HEIGHT_Z_MM = 46.0
BATTERY_RAIL_THICKNESS_MM = 3.0
BATTERY_RAIL_CLEARANCE_PER_SIDE_MM = 1.0
BATTERY_RAIL_HEIGHT_Z_MM = 8.0
BATTERY_RAIL_CORNER_RADIUS_MM = 4.0

# A removable tray sits above the battery, leaving about 34 mm beneath the lid
# for electronics.  Four standoffs remain outside the battery rail.
ELECTRONICS_TRAY_LENGTH_X_MM = 180.0
ELECTRONICS_TRAY_WIDTH_Y_MM = 132.0
ELECTRONICS_TRAY_THICKNESS_Z_MM = 3.0
ELECTRONICS_TRAY_BOTTOM_Z_MM = 56.0
ELECTRONICS_CLEAR_HEIGHT_Z_MM = (
    BODY_BASE_HEIGHT_Z_MM
    - 3.0
    - ELECTRONICS_TRAY_BOTTOM_Z_MM
    - ELECTRONICS_TRAY_THICKNESS_Z_MM
)
TRAY_STANDOFF_RADIUS_MM = 5.5
TRAY_STANDOFF_X_MM = 80.0
TRAY_STANDOFF_Y_MM = 55.0
TRAY_M3_PILOT_DIAMETER_MM = 2.8
TRAY_PILOT_DEPTH_MM = 8.0
TRAY_STANDOFF_CENTERS_XY_MM = (
    (-TRAY_STANDOFF_X_MM, -TRAY_STANDOFF_Y_MM),
    (-TRAY_STANDOFF_X_MM, TRAY_STANDOFF_Y_MM),
    (TRAY_STANDOFF_X_MM, -TRAY_STANDOFF_Y_MM),
    (TRAY_STANDOFF_X_MM, TRAY_STANDOFF_Y_MM),
)

# Four side-wall-supported bosses retain the removable lid.
LID_BOSS_RADIUS_MM = 6.5
LID_BOSS_BOTTOM_Z_MM = 72.0
LID_M3_INSERT_PILOT_DIAMETER_MM = 4.2
LID_INSERT_PILOT_DEPTH_MM = 8.0
LID_BOSS_X_MM = 98.0
LID_BOSS_Y_MM = 75.5
LID_BOSS_CENTERS_XY_MM = (
    (-LID_BOSS_X_MM, -LID_BOSS_Y_MM),
    (-LID_BOSS_X_MM, LID_BOSS_Y_MM),
    (LID_BOSS_X_MM, -LID_BOSS_Y_MM),
    (LID_BOSS_X_MM, LID_BOSS_Y_MM),
)

# High front/rear ventilation stays clear of the side hip pads.
VENT_SLOT_WIDTH_Y_MM = 18.0
VENT_SLOT_HEIGHT_Z_MM = 4.0
VENT_SLOT_Y_MM = (-45.0, -15.0, 15.0, 45.0)
VENT_SLOT_Z_MM = (74.0, 86.0)

# Symmetric service openings and utility mounting holes.  The side cable
# opening fits in the 36 mm clear strip between the two 84 mm hip backing
# pads, so neither body-side hip plate can cover it.  Bottom utility holes
# stay outside the battery rail and clear the electronics-tray standoffs.
SIDE_CABLE_PORT_LENGTH_X_MM = 24.0
SIDE_CABLE_PORT_HEIGHT_Z_MM = 14.0
SIDE_CABLE_PORT_CENTER_X_MM = 0.0
SIDE_CABLE_PORT_CENTER_Z_MM = 50.0
UTILITY_M2_CLEARANCE_DIAMETER_MM = 2.4
UTILITY_M3_CLEARANCE_DIAMETER_MM = 3.4
BASE_UTILITY_M2_X_MM = (-35.0, 35.0)
BASE_UTILITY_M3_X_MM = (-75.0, 75.0)
BASE_UTILITY_Y_MM = (-68.0, 68.0)

# Current official Bambu Lab X2D print envelopes.
X2D_MAIN_NOZZLE_VOLUME_MM = (256.0, 256.0, 260.0)
X2D_DUAL_NOZZLE_SHARED_VOLUME_MM = (235.5, 256.0, 256.0)
RECOMMENDED_BRIM_MM = 5.0


def _one_valid_solid(shape: Shape, label: str) -> Shape:
    solids = list(shape.solids())
    if len(solids) != 1 or not solids[0].is_valid:
        raise RuntimeError(
            f"{label} must be one connected valid solid; found {len(solids)} solids"
        )
    result = solids[0]
    result.label = label
    return result


def _rounded_prism(
    length_x_mm: float,
    width_y_mm: float,
    height_z_mm: float,
    *,
    minimum_z_mm: float,
    corner_radius_mm: float,
) -> Shape:
    blank = Box(
        length_x_mm,
        width_y_mm,
        height_z_mm,
        align=(Align.CENTER, Align.CENTER, Align.MIN),
    ).moved(Location((0.0, 0.0, minimum_z_mm)))
    return fillet(blank.edges().filter_by(Axis.Z), corner_radius_mm)


def make_outer_shell_blank() -> Shape:
    """Return the rounded exterior before hollowing or adding features."""
    return _rounded_prism(
        BODY_LENGTH_X_MM,
        BODY_WIDTH_Y_MM,
        BODY_BASE_HEIGHT_Z_MM,
        minimum_z_mm=0.0,
        corner_radius_mm=BODY_CORNER_RADIUS_MM,
    )


def make_inner_cavity_tool() -> Shape:
    """Return an overtravel cutter that leaves the wall and floor thickness."""
    return _rounded_prism(
        BODY_LENGTH_X_MM - 2.0 * BODY_WALL_MM,
        BODY_WIDTH_Y_MM - 2.0 * BODY_WALL_MM,
        BODY_BASE_HEIGHT_Z_MM - BODY_FLOOR_MM + BOOLEAN_OVERTRAVEL_MM,
        minimum_z_mm=BODY_FLOOR_MM,
        corner_radius_mm=BODY_CORNER_RADIUS_MM - BODY_WALL_MM,
    )


def make_hip_backing_pads() -> tuple[Shape, ...]:
    """Return four internal pads tied into the floor and top rim."""
    added_thickness = HIP_BACKING_TOTAL_THICKNESS_Y_MM - BODY_WALL_MM
    pad_center_y = (
        BODY_WIDTH_Y_MM / 2.0
        - BODY_WALL_MM
        - added_thickness / 2.0
    )
    pad_min_z = BODY_FLOOR_MM - FUSION_OVERLAP_MM
    return tuple(
        Box(
            HIP_BACKING_PAD_LENGTH_X_MM,
            added_thickness,
            HIP_BACKING_PAD_HEIGHT_Z_MM,
            align=(Align.CENTER, Align.CENTER, Align.MIN),
        ).moved(Location((x_mm, side * pad_center_y, pad_min_z)))
        for x_mm in HIP_MOUNT_CENTERS_X_MM
        for side in (-1.0, 1.0)
    )


def make_battery_retaining_rail() -> Shape:
    """Return a low rounded rail around the provisional battery envelope."""
    opening_length = (
        BATTERY_CLEAR_LENGTH_X_MM
        + 2.0 * BATTERY_RAIL_CLEARANCE_PER_SIDE_MM
    )
    opening_width = (
        BATTERY_CLEAR_WIDTH_Y_MM
        + 2.0 * BATTERY_RAIL_CLEARANCE_PER_SIDE_MM
    )
    outer = _rounded_prism(
        opening_length + 2.0 * BATTERY_RAIL_THICKNESS_MM,
        opening_width + 2.0 * BATTERY_RAIL_THICKNESS_MM,
        BATTERY_RAIL_HEIGHT_Z_MM + FUSION_OVERLAP_MM,
        minimum_z_mm=BODY_FLOOR_MM - FUSION_OVERLAP_MM,
        corner_radius_mm=BATTERY_RAIL_CORNER_RADIUS_MM,
    )
    inner = _rounded_prism(
        opening_length,
        opening_width,
        BATTERY_RAIL_HEIGHT_Z_MM + 2.0 * FUSION_OVERLAP_MM,
        minimum_z_mm=BODY_FLOOR_MM - FUSION_OVERLAP_MM,
        corner_radius_mm=max(
            BATTERY_RAIL_CORNER_RADIUS_MM - BATTERY_RAIL_THICKNESS_MM,
            0.5,
        ),
    )
    return _one_valid_solid(outer - inner, "battery_retaining_rail")


def make_tray_standoffs() -> tuple[Shape, ...]:
    """Return four floor-connected electronics-tray standoffs."""
    standoff_min_z = BODY_FLOOR_MM - FUSION_OVERLAP_MM
    standoff_height = ELECTRONICS_TRAY_BOTTOM_Z_MM - standoff_min_z
    return tuple(
        Cylinder(
            TRAY_STANDOFF_RADIUS_MM,
            standoff_height,
            align=(Align.CENTER, Align.CENTER, Align.MIN),
        ).moved(Location((x_mm, y_mm, standoff_min_z)))
        for x_mm, y_mm in TRAY_STANDOFF_CENTERS_XY_MM
    )


def make_lid_bosses() -> tuple[Shape, ...]:
    """Return four top bosses that overlap the side walls."""
    height = BODY_BASE_HEIGHT_Z_MM - LID_BOSS_BOTTOM_Z_MM
    return tuple(
        Cylinder(
            LID_BOSS_RADIUS_MM,
            height,
            align=(Align.CENTER, Align.CENTER, Align.MIN),
        ).moved(Location((x_mm, y_mm, LID_BOSS_BOTTOM_Z_MM)))
        for x_mm, y_mm in LID_BOSS_CENTERS_XY_MM
    )


def make_hip_mount_hole_tools() -> tuple[Shape, ...]:
    """Return eight cutters that drill matching holes through both side walls."""
    cutter_length = BODY_WIDTH_Y_MM + 2.0 * BOOLEAN_OVERTRAVEL_MM
    return tuple(
        Cylinder(
            HIP_BODY_CLEARANCE_DIAMETER_MM / 2.0,
            cutter_length,
            align=(Align.CENTER, Align.CENTER, Align.CENTER),
        )
        .rotate(Axis.X, 90.0)
        .moved(Location((x_mm, 0.0, z_mm)))
        for x_mm in HIP_MOUNT_HOLE_X_MM
        for z_mm in HIP_MOUNT_HOLE_Z_MM
    )


def make_tray_pilot_tools() -> tuple[Shape, ...]:
    """Return shallow M3 pilot cutters in the electronics standoffs."""
    start_z = ELECTRONICS_TRAY_BOTTOM_Z_MM - TRAY_PILOT_DEPTH_MM
    return tuple(
        Cylinder(
            TRAY_M3_PILOT_DIAMETER_MM / 2.0,
            TRAY_PILOT_DEPTH_MM + BOOLEAN_OVERTRAVEL_MM,
            align=(Align.CENTER, Align.CENTER, Align.MIN),
        ).moved(Location((x_mm, y_mm, start_z)))
        for x_mm, y_mm in TRAY_STANDOFF_CENTERS_XY_MM
    )


def make_lid_insert_pilot_tools() -> tuple[Shape, ...]:
    """Return provisional pilot cutters for user-selected M3 inserts."""
    start_z = BODY_BASE_HEIGHT_Z_MM - LID_INSERT_PILOT_DEPTH_MM
    return tuple(
        Cylinder(
            LID_M3_INSERT_PILOT_DIAMETER_MM / 2.0,
            LID_INSERT_PILOT_DEPTH_MM + BOOLEAN_OVERTRAVEL_MM,
            align=(Align.CENTER, Align.CENTER, Align.MIN),
        ).moved(Location((x_mm, y_mm, start_z)))
        for x_mm, y_mm in LID_BOSS_CENTERS_XY_MM
    )


def make_front_rear_vent_tools() -> tuple[Shape, ...]:
    """Return paired rectangular slots through the front and rear walls."""
    return tuple(
        Box(
            BODY_LENGTH_X_MM + 2.0 * BOOLEAN_OVERTRAVEL_MM,
            VENT_SLOT_WIDTH_Y_MM,
            VENT_SLOT_HEIGHT_Z_MM,
            align=(Align.CENTER, Align.CENTER, Align.CENTER),
        ).moved(Location((0.0, y_mm, z_mm)))
        for y_mm in VENT_SLOT_Y_MM
        for z_mm in VENT_SLOT_Z_MM
    )


def make_side_cable_port_tool() -> Shape:
    """Return one rounded cutter that opens a service port in each side wall."""
    radius = SIDE_CABLE_PORT_HEIGHT_Z_MM / 2.0
    straight_length = SIDE_CABLE_PORT_LENGTH_X_MM - 2.0 * radius
    cutter_length_y = BODY_WIDTH_Y_MM + 2.0 * BOOLEAN_OVERTRAVEL_MM
    center_box = Box(
        straight_length,
        cutter_length_y,
        SIDE_CABLE_PORT_HEIGHT_Z_MM,
        align=(Align.CENTER, Align.CENTER, Align.CENTER),
    ).moved(
        Location(
            (
                SIDE_CABLE_PORT_CENTER_X_MM,
                0.0,
                SIDE_CABLE_PORT_CENTER_Z_MM,
            )
        )
    )
    cap_offset_x = straight_length / 2.0
    caps = tuple(
        Cylinder(
            radius,
            cutter_length_y,
            align=(Align.CENTER, Align.CENTER, Align.CENTER),
        )
        .rotate(Axis.X, 90.0)
        .moved(
            Location(
                (
                    SIDE_CABLE_PORT_CENTER_X_MM + side * cap_offset_x,
                    0.0,
                    SIDE_CABLE_PORT_CENTER_Z_MM,
                )
            )
        )
        for side in (-1.0, 1.0)
    )
    return center_box.fuse(*caps)


def make_base_utility_mount_hole_tools() -> tuple[Shape, ...]:
    """Return M2/M3 clearance cutters through the protected floor rails."""
    cutter_height = BODY_FLOOR_MM + 2.0 * BOOLEAN_OVERTRAVEL_MM
    cutter_min_z = -BOOLEAN_OVERTRAVEL_MM
    m2_tools = tuple(
        Cylinder(
            UTILITY_M2_CLEARANCE_DIAMETER_MM / 2.0,
            cutter_height,
            align=(Align.CENTER, Align.CENTER, Align.MIN),
        ).moved(Location((x_mm, y_mm, cutter_min_z)))
        for x_mm in BASE_UTILITY_M2_X_MM
        for y_mm in BASE_UTILITY_Y_MM
    )
    m3_tools = tuple(
        Cylinder(
            UTILITY_M3_CLEARANCE_DIAMETER_MM / 2.0,
            cutter_height,
            align=(Align.CENTER, Align.CENTER, Align.MIN),
        ).moved(Location((x_mm, y_mm, cutter_min_z)))
        for x_mm in BASE_UTILITY_M3_X_MM
        for y_mm in BASE_UTILITY_Y_MM
    )
    return m2_tools + m3_tools


def make_body_base() -> Shape:
    """Return the complete one-piece open-top structural tub."""
    shell = make_outer_shell_blank() - make_inner_cavity_tool()
    reinforced = shell.fuse(
        *make_hip_backing_pads(),
        make_battery_retaining_rail(),
        *make_tray_standoffs(),
        *make_lid_bosses(),
    )
    finished = reinforced - (
        make_hip_mount_hole_tools()
        + make_tray_pilot_tools()
        + make_lid_insert_pilot_tools()
        + make_front_rear_vent_tools()
        + (make_side_cable_port_tool(),)
        + make_base_utility_mount_hole_tools()
    )
    return _one_valid_solid(finished, "quadruped_body_base")


def x2d_print_footprint_with_brim() -> tuple[float, float, float]:
    """Return the body base print envelope including the recommended brim."""
    brim_allowance = 2.0 * RECOMMENDED_BRIM_MM
    return (
        BODY_LENGTH_X_MM + brim_allowance,
        BODY_WIDTH_Y_MM + brim_allowance,
        BODY_BASE_HEIGHT_Z_MM,
    )


def gen_step() -> Shape:
    """Return the STEP-ready one-piece quadruped body base."""
    return make_body_base()


if __name__ == "__main__":
    from build123d import export_step

    output_path = PROJECT_ROOT / "exports" / "step" / "quadruped_body_base.step"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    export_step(gen_step(), output_path)
    print(f"Generated {output_path}")
