"""Pure-RL, vectorized Drobot stair task registration."""

import gymnasium as gym

from . import agents

gym.register(
    id="Drobot-Pure-Stairs-Direct",
    entry_point=f"{__name__}.pure_stairs_env:DrobotPureStairsEnv",
    disable_env_checker=True,
    kwargs={
        "env_cfg_entry_point": f"{__name__}.pure_stairs_env_cfg:DrobotPureStairsEnvCfg",
        "rsl_rl_cfg_entry_point": (
            f"{agents.__name__}.rsl_rl_ppo_cfg:DrobotPureStairsPPORunnerCfg"
        ),
    },
)


def _register_variant(task_id: str, env_cfg: str, runner_cfg: str) -> None:
    gym.register(
        id=task_id,
        entry_point=f"{__name__}.pure_stairs_env:DrobotPureStairsEnv",
        disable_env_checker=True,
        kwargs={
            "env_cfg_entry_point": f"{__name__}.pure_stairs_env_cfg:{env_cfg}",
            "rsl_rl_cfg_entry_point": (
                f"{agents.__name__}.rsl_rl_ppo_cfg:{runner_cfg}"
            ),
        },
    )


_register_variant(
    "Drobot-Pure-Stairs-Hip-Direct",
    "DrobotPureStairsHipEnvCfg",
    "DrobotPureStairsHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-Low-Hip-Direct",
    "DrobotPureStairsLowHipEnvCfg",
    "DrobotPureStairsLowHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-Sideways-Hip-Direct",
    "DrobotPureStairsSidewaysHipEnvCfg",
    "DrobotPureStairsSidewaysHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Hip-Direct",
    "DrobotPureStairsFirstStepHipEnvCfg",
    "DrobotPureStairsFirstStepHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Landing-Hip-Direct",
    "DrobotPureStairsFirstStepLandingHipEnvCfg",
    "DrobotPureStairsFirstStepLandingHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Landing-Long-Hip-Direct",
    "DrobotPureStairsFirstStepLandingHipEnvCfg",
    "DrobotPureStairsFirstStepLandingLongHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Landing-Consolidate-Hip-Direct",
    "DrobotPureStairsFirstStepLandingConsolidateHipEnvCfg",
    "DrobotPureStairsFirstStepLandingConsolidateHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Contact-Retention-Hip-Direct",
    "DrobotPureStairsFirstStepContactRetentionHipEnvCfg",
    "DrobotPureStairsFirstStepContactRetentionHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Broad-Support-Retention-Hip-Direct",
    "DrobotPureStairsFirstStepBroadSupportRetentionHipEnvCfg",
    "DrobotPureStairsFirstStepBroadSupportRetentionHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Width105-Support-Retention-Hip-Direct",
    "DrobotPureStairsFirstStepWidth105SupportRetentionHipEnvCfg",
    "DrobotPureStairsFirstStepWidth105SupportRetentionHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Width90-Support-Retention-Hip-Direct",
    "DrobotPureStairsFirstStepWidth90SupportRetentionHipEnvCfg",
    "DrobotPureStairsFirstStepWidth90SupportRetentionHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Width105-Rise10-Hip-Direct",
    "DrobotPureStairsFirstStepWidth105Rise10HipEnvCfg",
    "DrobotPureStairsFirstStepWidth105Rise10HipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Width105-Low25-Hip-Direct",
    "DrobotPureStairsFirstStepWidth105Low25HipEnvCfg",
    "DrobotPureStairsFirstStepWidth105Low25HipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Width105-Low50-Hip-Direct",
    "DrobotPureStairsFirstStepWidth105Low50HipEnvCfg",
    "DrobotPureStairsFirstStepWidth105Low50HipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Width105-Low25-To37-Hip-Direct",
    "DrobotPureStairsFirstStepWidth105Low25To37HipEnvCfg",
    "DrobotPureStairsFirstStepWidth105Low25To37HipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Width105-Low37-Hip-Direct",
    "DrobotPureStairsFirstStepWidth105Low37HipEnvCfg",
    "DrobotPureStairsFirstStepWidth105Low37HipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Width105-Low75-Hip-Direct",
    "DrobotPureStairsFirstStepWidth105Low75HipEnvCfg",
    "DrobotPureStairsFirstStepWidth105Low75HipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Width105-Low100-Hip-Direct",
    "DrobotPureStairsFirstStepWidth105Low100HipEnvCfg",
    "DrobotPureStairsFirstStepWidth105Low100HipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Width105-Low25-Consolidate-Hip-Direct",
    "DrobotPureStairsFirstStepWidth105Low25HipEnvCfg",
    "DrobotPureStairsFirstStepWidth105Low25ConsolidateHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Landing-Low-Hip-Direct",
    "DrobotPureStairsFirstStepLandingLowHipEnvCfg",
    "DrobotPureStairsFirstStepLandingLowHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Landing-Sideways-Hip-Direct",
    "DrobotPureStairsFirstStepLandingSidewaysHipEnvCfg",
    "DrobotPureStairsFirstStepLandingSidewaysHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Close1-Hip-Direct",
    "DrobotPureStairsFirstStepClose1HipEnvCfg",
    "DrobotPureStairsFirstStepClose1HipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Close2-Hip-Direct",
    "DrobotPureStairsFirstStepClose2HipEnvCfg",
    "DrobotPureStairsFirstStepClose2HipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Close4-Hip-Direct",
    "DrobotPureStairsFirstStepClose4HipEnvCfg",
    "DrobotPureStairsFirstStepClose4HipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-First-Step-Close6-Hip-Direct",
    "DrobotPureStairsFirstStepClose6HipEnvCfg",
    "DrobotPureStairsFirstStepClose6HipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-Foot-Lift-Hip-Direct",
    "DrobotPureStairsFootLiftHipEnvCfg",
    "DrobotPureStairsFootLiftHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-Foot-Lift-Consolidate-Hip-Direct",
    "DrobotPureStairsFootLiftConsolidateHipEnvCfg",
    "DrobotPureStairsFootLiftConsolidateHipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-Foot-Lift-10-Hip-Direct",
    "DrobotPureStairsFootLift10HipEnvCfg",
    "DrobotPureStairsFootLift10HipPPORunnerCfg",
)
_register_variant(
    "Drobot-Pure-Stairs-Foot-Lift-14-Hip-Direct",
    "DrobotPureStairsFootLift14HipEnvCfg",
    "DrobotPureStairsFootLift14HipPPORunnerCfg",
)
